# Generated by Django 4.1.7 on 2023-04-01 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Дата рождения"
            ),
        ),
    ]
