# Generated by Django 4.1.7 on 2023-04-02 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                validators=[
                    django.core.validators.EmailValidator(
                        allowlist=["mail.ru", "yandex.ru"]
                    )
                ],
                verbose_name="Почта",
            ),
        ),
    ]
