# Generated by Django 4.1.7 on 2023-04-02 08:11

from django.db import migrations, models
import utils.model_validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                validators=[
                    utils.model_validators.EmailDomainValidator(
                        available_domains=["mail.ru", "yandex.ru"]
                    )
                ],
                verbose_name="Почта",
            ),
        ),
    ]
